jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:+hYS81KSrDvnTw6BB4h2UeE=,iv:fHquN9vOSZW/Jiy8YPoAmoL3vWzyOHPlalOwr79Wdz8=,tag:xQl+h3oRopS97v+1ETL30g==,type:str]
                client_secret: ENC[AES256_GCM,data:yl0drsU958gzocnczv4pTgdeA4NYwlM3z+FrVm3/R0sE6FfEWqghUZHXihbRyik7QIRIIlx/u8gmvIbuiP9ADg==,iv:GI++3oMef9OG3rtO8Az3H0Y9iTXRDVpt80nLSn/6azg=,tag:VBSmSDqE5vtUxf/Of/XlUQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:58Z"
          enc: CiQA67O9AK2027WGYGTzywa01Cz+Ez7sOTk/d9payovyK5pg8g4SSADmhpq89bbIWFjlGg79o/iupJ4anLU5Ab9VL+qNzhu6e83JtJ7wSv6sK+cDiEfVSaKQ1YIcadDXFt4WUKRt7MFvAa1sLqp2LA==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-20T01:41:58Z"
    mac: ENC[AES256_GCM,data:h5SYh52DCOcU1QsluMpVHCdi3Mfjj4HEEhSW8YLEKx67ylFym5zO0RGo8YdW1KLQ3rnBkrUNAubx6IzRokAR84fPdKxvTQVLLqqXM5kxTrgKivGrzh2O1YWGh6hWmwVpdMclauPSYJd7p65BEJnucE94+VBZMfRM2v261FHIG3I=,iv:7ctGMZEQnD8NWD10OjeaxDUOOOPoikAfehqUSaaFVeM=,tag:q2ND0/qwEF6fouYLVaywvw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
