jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:0ZbWMSpIZ5XkT/aRpDVvFyU=,iv:a45Q4GMwmjejpxcUIxTbTDC/yLQqBw3bSEroMTpqUfI=,tag:s4DEPpBgreV4gtMPZPF0mw==,type:str]
                client_secret: ENC[AES256_GCM,data:bqWbAQU9Xuyp/tTZMXlN+ukH1NTZgEfgJsqoMvIBucvUjlcloV/CARyaEUDbbejTW0GWaAR6BLSy+4uTOHDsRw==,iv:5HzMJPFJmYF5CnhcbFyOlLvJie0Czl9erhQcU365ba8=,tag:oeL1WIdl3Gaf8hoe/0KexA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:58Z"
          enc: CiQA67O9ALEiz+lgnWQQgjT08Fx2+SUNdWEA2MqdIoEl0Ett3zASSQDmhpq85T+08Rtt/sqeMktjA6t8rCVH8soCR/sNJwDHgXabOipn/od+64D/L+aggCaXqJ433twByk0+YUJAe5z733oW/3J53eU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-20T01:39:12Z"
    mac: ENC[AES256_GCM,data:j6HEQIoRQ3b83owurMMur2osjVnQM1J4sZU99WEyBTThLlmbg7iY0MXGINvh4DNPaY7A2CnVIWPMrY/6aCmQZoYKBApBW06ThHlrCYXF7f+SZg/OCjzzpW9ZmrNOGmyIvROKjLK45OZawoKJbOBw/saufzaq2M1aIdAzg5+vQvQ=,iv:1jtjlsxIPgcLQOdLswWHczzKPdL+Aho5HpAKDIiqZSc=,tag:YTvymYhzN5o/e7rJvPMFxg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
