nfsPVC:
  nfs:
    shareName: export/homedirs-other-2020-07-29/accessibility/prod

jupyterhub:
  ingress:
    enabled: true
    hosts:
      - accessibility.datahub.berkeley.edu
    tls:
      - secretName: tls-cert
        hosts:
          - accessibility.datahub.berkeley.edu
  hub:
    config:
      GenericOAuthenticator:
        extra_params:
          client_id: service-accessibility.datahub.berkeley.edu
        client_id: service-accessibility.datahub.berkeley.edu
        authorize_url: https://datahub.berkeley.edu/hub/api/oauth2/authorize
        token_url: https://datahub.berkeley.edu/hub/api/oauth2/token
        userdata_url: https://datahub.berkeley.edu/hub/api/user
      CanvasOAuthenticator:
        client_id: '10720000000000472'
        oauth_callback_url: 'https://accessibility.berkeley.edu/hub/oauth_callback'
    db:
      pvc:
        # This also holds logs
        storage: 4Gi
