nfsPVC:
  nfs:
    shareName: export/homedirs-other-2020-07-29/accessibility/staging

jupyterhub:
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - accessibility-staging.datahub.berkeley.edu
    tls:
      - secretName: tls-cert
        hosts:
          - accessibility-staging.datahub.berkeley.edu
  hub:
    config:
      GenericOAuthenticator:
        extra_params:
          client_id: service-accessibility-staging.datahub.berkeley.edu
        client_id: service-accessibility-staging.datahub.berkeley.edu
        authorize_url: https://staging.datahub.berkeley.edu/hub/api/oauth2/authorize
        token_url: https://staging.datahub.berkeley.edu/hub/api/oauth2/token
        userdata_url: https://staging.datahub.berkeley.edu/hub/api/user
      CanvasOAuthenticator:
        client_id: '10720000000000472'
        oauth_callback_url: 'https://accessibility-staging.berkeley.edu/hub/oauth_callback'
