nfsPVC:
  nfs:
    shareName: export/homedirs-other-2020-07-29/workshop/staging

jupyterhub:
  scheduling:
    userScheduler:
      replicas: 1
  ingress:
    enabled: true
    hosts:
      - workshop-staging.datahub.berkeley.edu
    tls:
      - secretName: tls-cert
        hosts:
          - workshop-staging.datahub.berkeley.edu
