jupyterhub:
  prePuller:
    continuous:
      enabled: false
  proxy:
    service:
      loadBalancerIP: 34.135.56.190
    https:
      hosts:
        - hubv2-staging.data8x.berkeley.edu
  hub:
    services:
      gofer_nb:
        url: http://grader-staging.data8x.berkeley.edu:10101
