jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:uY3fBC8M/ruLpNhBrvskDmA=,iv:pgh//+Nha75iKK8oRvGt2khibGFbJC6PchvVLwULJMM=,tag:q69bvUlfIviEVHVdG6tC3A==,type:str]
                client_secret: ENC[AES256_GCM,data:CaQz8IiT5hAOGYdc3viZyxLvbh0mWIuuvNyv4bim2upVncvKl+Az2j0ZF0vEV7CGUq41fJH4pO4k310Yl79Qiw==,iv:6mssw6RooRV1ul1yR+XagtENhwLXImPgpocvnAViFSo=,tag:gWHRcXkBUzqR6bbWkB5hMA==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:qTirIL6zgNNkeQbQVgd+e4s3DpxxOeiIt63wnbAhCRf/7INtsVnc5YBvxw==,iv:rXL28s2b/d7bOmzKFf9YxwlGkp4Fkstq8mZgrmpEXsQ=,tag:/Q/lgYyAGKhATeIcpiPttw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:58Z"
          enc: CiQA67O9AK2027WGYGTzywa01Cz+Ez7sOTk/d9payovyK5pg8g4SSADmhpq89bbIWFjlGg79o/iupJ4anLU5Ab9VL+qNzhu6e83JtJ7wSv6sK+cDiEfVSaKQ1YIcadDXFt4WUKRt7MFvAa1sLqp2LA==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-20T23:44:39Z"
    mac: ENC[AES256_GCM,data:YRp2gVU3js/NJkjYIhR1V50cGHZyhgKERjnIrapB9ONUdmmOaasHA71Txi1i64keyo5m/hmoMwQspozGKRV4qVWop5O57ESTbhKchNTO830Du2UOho6ftl14WyDAbnheCgqoZHAijS4+5GGgyCH5rvSEwnRPu3qhpmzWCYxcWPM=,iv:+LFNKE8mMweQNpGutdJFiEkZT34fpDq3Qs0O0m1cIAI=,tag:OBaAYE6HK7HoQhLqRAa0AQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
