jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:oVqQjcJvcw7paOGDB88g1Hw=,iv:p/ZkoTdQd4s2tR3xbtTJzRcCzkQVAGYWhPubH2uimxU=,tag:GEgHQLOeC6rPGV+0Ve5deA==,type:str]
                client_secret: ENC[AES256_GCM,data:0Anb/EdSDB9Cumo4ePWbA98QIBYLDxlfciZLKyjZdOhpr7KyWqLAiin10IjGw/INS8XpBByZKYtswOHdMkbh6g==,iv:QESXOS/htLsNgVvkYw+iGBoL0/Ce7ubxNdP1iS8WOmU=,tag:UZEK+/C3AG3rDfB2+sR6MQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:eCEWrt92BM2wbszo+TQU7+g8sE6TaATzneTkL/ykeeZzfGe7gd+jbvkZr10Xk6wZThpD,iv:NGrT/Q30RwupFLwuRJV0oI4yMs2crjbfMzlfIFPmW+A=,tag:q78JRv69MmwjDdDryc3ajw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:58Z"
          enc: CiQA67O9ALEiz+lgnWQQgjT08Fx2+SUNdWEA2MqdIoEl0Ett3zASSQDmhpq85T+08Rtt/sqeMktjA6t8rCVH8soCR/sNJwDHgXabOipn/od+64D/L+aggCaXqJ433twByk0+YUJAe5z733oW/3J53eU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-20T23:41:33Z"
    mac: ENC[AES256_GCM,data:jaHc4wv2le30pDeefo+Bb7vo9gidaZt4+e4D1vDg0I6JqCFBFGyYYkmjsEl+OMwslicdFLh25JF+j+HjaqyH+cJPGTH7F8n0s0rgk9DoIklLM+6A9doyWphcvgaGU7JKc70K1LfLMw3zjuxIyP+hrl2m/mv7G0fl48atttHy57o=,iv:lb6GNGyknIItCo7KKXtKa4pHxbv8pJNvp43Y+CLcCTI=,tag:I3f7CEvU5fTG2YJrn2+fBw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
