nfsPVC:
  enabled: true
  nfs:
    serverIP: 10.128.0.62
    shareName: export/edxhomes-staging-2023-10-17
jupyterhub:
  prePuller:
    continuous:
      enabled: false
  proxy:
    service:
      loadBalancerIP: 34.135.56.190
    https:
      hosts:
        - edx-staging.datahub.berkeley.edu
  hub:
    services:
      otter_grade:
        url: http://grader-srv-staging.datahub.berkeley.edu:10101
