nfsPVC:
  enabled: true
  nfs:
    serverIP: 10.50.250.234

jupyterhub:
  scheduling:
    userScheduler:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2023-12-21
  proxy:
    chp:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2023-12-21
    traefik:
      nodeSelector:
        hub.jupyter.org/pool-name: core-pool-2023-12-21

  hub:
    nodeSelector:
      hub.jupyter.org/pool-name: core-pool-2023-12-21
    config:
      Authenticator:
        admin_users:
            # infrastructure
            - balajialwar
            - felder
            - gmerritt
            - rylo
            - sknapp

            # List of other admin users
            - rbarreto
            - pratik.sachdeva
            - aculich
            - cheng.ren
            - emily_grabowski
            - klganter
            - cvacano
  singleuser:
    nodeSelector:
      hub.jupyter.org/pool-name: dlab-pool
    storage:
      type: static
      static:
        pvcName: home-nfs-v3
        subPath: "{username}"
    memory:
      guarantee: 4G
      limit: 8G
    image: {}
